# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74fdbaf25bcffd8b86616664d7e8b110d33605a72cc0894e05f6c6c4f9afb7fc0ad128f808f2f0cf89c8a8d622e2155305a868337300788d8d2ec007a9bdd54

test:
  secret_key_base: 96a40e83546e1f586db2307141764f58475abbf4bcf249059e881db558326c000ed3d76b0dbc6ab446fa16922076c05b7cfa6e2aae36a8a4ac50228e69e78991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
